version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  supvision:
    build: ./supvision
    container_name: supvision
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/venom
      - FLASK_ENV=development
      - FLASK_APP=app.py
    working_dir: /app
    volumes:
      - ./supvision:/app   # live code mounting 
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0 --port=5000 --reload


  model_server:
    build: ./model_server
    container_name: model_server
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/venom
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "8000:8000"
    volumes:
      - ./model_server:/app   # live code mounting
    command: python app.py
volumes:
  mongo-data: