version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: supvision-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  flask-app:
    build: .
    container_name: supvision-app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/venom
      - FLASK_ENV=development
    ports:
      - "8000:8000"
    volumes:
      - .:/app   # live code mounting
    command: flask run --host=0.0.0.0 --port=8000 --reload

  model-server:
    build: .
    container_name: supvision-model-server
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/venom
      - FLASK_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/app   # live code mounting
    command: python model_server/app.py

volumes:
  mongo-data:
